# Generated by Django 4.0.5 on 2022-07-05 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('conn_time', models.IntegerField(default=0)),
                ('device_id', models.CharField(default='', max_length=15)),
                ('uid', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('last_res', models.IntegerField(default=0)),
                ('net', models.CharField(default='', max_length=21)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('gps', models.BooleanField(default=False)),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('direction', models.IntegerField(default=0)),
                ('altitude', models.IntegerField(default=0)),
                ('satellite_count', models.IntegerField(default=0)),
                ('gsm_signal', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('step', models.IntegerField(default=0)),
                ('turn', models.IntegerField(default=0)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_power', models.BooleanField(default=False)),
                ('wear', models.BooleanField(default=False)),
                ('static', models.BooleanField(default=False)),
                ('sos', models.BooleanField(default=False)),
                ('low_power_warn', models.BooleanField(default=False)),
                ('break_warn', models.BooleanField(default=False)),
                ('fall_warn', models.BooleanField(default=False)),
                ('device_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceinfo')),
            ],
        ),
    ]
