# Generated by Django 4.0.5 on 2022-07-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_deviceinfo_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxstart',
            name='oxygen',
            field=models.IntegerField(default=0),
        ),
    ]
